### ISSUE TITLE
4.05 compatibility

### ISSUE THREAD

**Issue by gasche** [yoriyuki/Camomile#21] opened 2017-02-25 03:54 UTC
I am trying to get Camomile working on 4.05. So far I discovered the following issues:

1. There are some patches distributed with the `opam` package that are not currently merged upstream, and which I needed to test the 4.05 build (in particular the patch that removes the camlp4o dependency, given that Camlp4 is not currently packaged for 4.05). Should I consider sending these patches here for maintainers to consider them for inclusion? (I have no idea what their content is, but merged them in my testing branch as 8244e5d7d543f0f7303e66a4667da0b32cf2d4de and 2349f9983cac757ced9aa43bead7ea2c9ff687c3 .) (After giving them a look, the no-camlp4 patch seems to just change the parser into its post-processed version, so I guess it makes sense to keep distributing separately and not stored the camlp4-generated files in version control, but maybe that could be pointed out in the README or somewhere?)

2. There is an obviously-safe, minor change that is required by a modification of the type-checker behavior in 4.05, I sent a patch in #20.

3. In the current 4.05 branch, `Bigarray` seems to depend on `Unix` because of the change in ocaml/ocaml#997. This breaks the Camomile build, which list `.cma` dependencies by hand and lists `bigarray.cma` but (of course?) not `unix.cma`. I have patched Camomile locally to go further with the build (see my working [4.05-fixes](https://github.com/gasche/Camomile/tree/4.05-fixes) branch which contains all the changes I currently have stacked to test the build), but it is not clear to me that changing Camomile is the right move here: it might be considered a regression in the standard library, and fixed at this level, requiring no Camomile change.

4. Finally, once all these changes are applied, I see a surprising error when building Camomile, that occurs when building under 4.05 but not under 4.04:

```
tools/camomilelocaledef.opt --file locales/test_1.txt locales 
Fatal error: exception File "toolslib/absCe.ml", line 163, characters 19-25: Assertion failed
Makefile:360: recipe for target 'locales/test_1.mar' failed
make: *** [locales/test_1.mar] Error 2
```

This may be a bug in the 4.05.0+beta2 compiler or runtime, or at least a change in behavior that breaks Camomile. I don't know/understand the codebase to have an idea of what causes it, but it is worth investigating more.

**Comment by gasche** [comment] 2017-02-25 16:46
(After more discussion upstream, it is clear that the `Bigarray` problem will be resolved soon, so that no change on the Camomile side is required.)

**Comment by gasche** [comment] 2017-02-26 01:00
@michipili, @seliopou: I am worried about the "Assertion failed" problem that may be a 4.05 regression, but I don't know the Camomile codebase enough to understand what is going on. Any help from you to identify the root of the issue (and whether it looks like an ocaml-side bug) would be warmly welcome.

**Comment by yoriyuki** [comment] 2017-02-26 08:08
Did "Assertion failed" appear early versions?  The problem is caused by someone trying to compare two characters in `Quaternary level precision using AbsCe.  This should not happen, because comparison in `Quaternary level precision is always done by algorithmically using code points of characters.

If this error happens in earlier versions of OCaml, this could be a bug in Camomile (but I have no idea when the bug enter the code).  Otherwise, this could be a serious bug in OCaml, possibly related to polymorphic variants.

**Comment by gasche** [comment] 2017-02-26 12:34
Thanks! I believe that the error is indeed new to 4.05 -- I can give it another try in case it was build environment thing. Because it occurs during the normal build process, I suppose that it would have been caught before.

**Comment by gasche** [comment] 2017-02-26 16:08
I did more test. I can confirm that the problem is new to 4.05 -- the build, including this test, works fine in 4.04. 
What I also noticed is that while `tools/camomilelocaledef.opt --file locales/test_1.txt locales` fails, the same thing with `tools/camomilelocaledef.byte` works correctly, even under 4.05. So there is a failure with the native-compiled tool, but not with the bytecode-compiled tool.

I thus suspected that this may be related to [MPR#7346](https://caml.inria.fr/mantis/view.php?id=7346), which is a reported difference in evaluation order between ocamlc and ocamlopt, and has been fixed in trunk (4.06+dev) but not in the 4.05 release branch. So I tried to build Camomile from trunk: it also fails, so this does not seem related to MPR#7346.

Note that the existence of a difference in evaluation order between byte- and native-compiled programs is not a sure sign of a bug in the compiler. It may be that the program is wrongly relying on an unspecified evaluation order. That said, even if that was the case, a previously-unknown difference in behavior between byte- and native-compiled program would be worthy of an issue report and possibly of an upstream change.

**Comment by gasche** [comment] 2017-02-26 17:05
I have tested that reverting either GPR#966 or GPR#967 (the two obvious evaluation-order-related changes in 4.05) does not fix the build failure. I will try a more classic bisection of 4.05 changes.

**Comment by yoriyuki** [comment] 2017-02-26 17:14
I don't see how the issue is related to evaluation order.  The assertion states that ``Quaternary` polymorphic variant somehow enters into `AbsCe.prev`, which should not happen. (I agree that it should not be checked by runtime, because it can be checked in compile time.  But this is another issue.) 

IIRC, polymorphic variants is converted to integers by hash.  Do we find finally a hash collision?

**Comment by gasche** [comment] 2017-02-26 17:17
The reason why I test for evaluation order is that it is the classic source of difference in behavior between the bytecode and native compiler. I don't know how the `Quaternary` variant is produced by Camomile, it could have been the result of a computation that does side-effects in some order, and might return something else with a different order. (You seem to say that is note the case).

Re hash conflicts: I think that there is a test at compile-time that distinct variants all get hashed differently, so I don't think that user program can be bitten by this without a compilation failure.

**Comment by yoriyuki** [comment] 2017-02-26 17:38
> I don't know how the Quaternary variant is produced by Camomile, it could have been the result of a computation that does side-effects in some order, and might return something else with a different order. (You seem to say that is not the case).

It is theoretically possible, but the Quaternary variant is not used for a complex computation.  It is just used as an optional argument to change the behavior of functions.

I quickly searched the source and I could not find any place where the Quaternary variant can enter `AbsCe.prev`.  It is only used in `toolslib/colParser.mly`, and in all calls to `AbsCe.prev`, it checks that the argument is not Quaternary.

One possibility is to change the type signature of `AbsCe.prev` to see where Quaternary variant enters this function.

**Comment by yoriyuki** [comment] 2017-02-26 17:54
> One possibility is to change the type signature of AbsCe.prev to see where Quaternary variant enters this function.

I did.  I changed the type signature of AbsCe.prev from UCol.prev to `[`Primary | `Secondary |`Tertiary] `.  It compiles and runs fine.  (I use ocaml 4.02.1)  So there is no possibility to enter Quaternary into `AbsCe.prev`.

**Comment by gasche** [comment] 2017-02-26 18:03
A value that the type-checker can rule out! You have convinced me that this is a compiler bug. I am bisecting to find the guilty change and will report upstream (and here). Thanks a lot for your help.

**Comment by gasche** [comment] 2017-02-26 18:55
Indeed, the issue came from a faulty optimization acting on the polymorphic variants. We will get a fix in 4.05 upstream.

**Comment by gasche** [comment] 2017-02-26 19:08
@yoriyuki given the various investigations, I believe that the pull request #20 is the only change that is required on Camomile's side for 4.05 compatibility (we will see about the Unix dependency thing, it may or may not require a change later). I would thus recommend merging it.

My plan is to apply the change as a patch to Camomile's released OPAM package, so that, as soon as the two other issues are fixed upstream, we existing Camomile version can be built under 4.05, and the packages that depend on it can themselves be tested under 4.05 under the release.

**Comment by yoriyuki** [comment] 2017-02-26 19:23
Yes.  now I'm checking that it builds safely in my environment.

**Comment by yoriyuki** [comment] 2017-02-26 19:55
#20 Merged.  I close the issue.  Please reopen if you find other changes are necessary to 4.05 compatibility.

**Closed by yoriyuki** 2017-02-26 19:55 UTC

**Comment by gasche** [comment] 2017-02-26 20:01
Thanks! I don't expect to find any further issue (with all the fixes in my experimental branch, I was able to build Camomile). I will reopen if the Unix dependency is not reverted upstream, to add it to Camomile.
